# Generated by Django 3.1.7 on 2021-03-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='tipomaterial',
            old_name='tipo',
            new_name='nome',
        ),
    ]
